### ISSUE TITLE
Add Hasura backend

### ISSUE THREAD

**Issue by cpursley** [hgiasac/ra-hasura-typescript-boilerplate#2]
Awesome boilerplate!

Could you add the Hasura backend (perhaps Hasura CLI with docker-compose), a remote backend or the Hasura migration (metadata and schema) scripts?

This would make it easier to demonstrate the boilerplate.

**Comment by hgiasac** [comment]
@cpursley Actually I separate frontend and backend in another repository

https://github.com/hgiasac/hasura-typescript-boilerplate

I will update docs for backend links
