### ISSUE TITLE
Error: Environment DATA_DOMAIN doesn't exist

### ISSUE THREAD

**Issue by cpursley** [hgiasac/ra-hasura-typescript-boilerplate#3]
It seems that even after changing `dotenv` => `.env` had no affect.

**Comment by hgiasac** [comment]
@cpursley This is because of parcel cache. Can you delete `.parcel-cache` folder then rerun again?

**Comment by cpursley** [comment]
Okay, I deleted cache and also installed parcel globally via npm (make sure to add to README).

After getting past that I'm seeing this error:

```
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: http://localhost:1234/ra-hasura-typescript-boilerplate.b1dc62cc.js
Source Map URL: ra-hasura-typescript-boilerplate.b1dc62cc.js.map
``` 

Thanks for you help :)

**Comment by hgiasac** [comment]
@cpursley You can ignore that warning. It is from dev tools. I plan replacing `parcel` to `rollup.js`, because parcel isn't stable for now. However, I don't have time yet

**Comment by hgiasac** [comment]
closed in https://github.com/hgiasac/ra-hasura-typescript-boilerplate/commit/18692fddeaef9786a9c2e5be499cb06b3d5bb491 and #4
